# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6091fe629c37b84e623220d6b940028191875b6fe462ad9dd8686e6c5b32754cbb2420493c28fae80deb9b8630e95083dcaa68f8ab92b1380e83814ce61c0e76

test:
  secret_key_base: 89ae7f5df3ff243c500f2520b89ad2fde8666d66556856451286c0adae24f2c305401dfb6426c62bb824bb975c968811f9ab8dbcc03e703728670b617a9acf8c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
